# Generated by Django 4.1.1 on 2022-11-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekujuru_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=99)),
            ],
        ),
        migrations.RenameModel(
            old_name='Genre',
            new_name='Days',
        ),
        migrations.RenameModel(
            old_name='Season',
            new_name='Genres',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='anime_season',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='genres',
            old_name='season',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='anime_genre',
        ),
        migrations.AddField(
            model_name='anime',
            name='season',
            field=models.ManyToManyField(to='sekujuru_app.seasons'),
        ),
    ]
