# Generated by Django 4.1.1 on 2022-11-06 10:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sekujuru_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='AnimePlatform',
        ),
        migrations.RenameModel(
            old_name='AnimePlatforms',
            new_name='Day',
        ),
        migrations.RenameModel(
            old_name='Days',
            new_name='Genre',
        ),
        migrations.RenameModel(
            old_name='Seasons',
            new_name='Season',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='WebUser',
        ),
    ]
