# Generated by Django 4.1.1 on 2022-11-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekujuru_app', '0002_seasons_rename_genre_days_rename_season_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='day',
            field=models.ManyToManyField(to='sekujuru_app.days'),
        ),
    ]
