# Generated by Django 4.1.1 on 2022-11-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekujuru_app', '0002_rename_genres_animeplatform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='day',
            field=models.ManyToManyField(to='sekujuru_app.day'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.ManyToManyField(to='sekujuru_app.genre'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platform',
            field=models.ManyToManyField(to='sekujuru_app.animeplatform'),
        ),
    ]
