# Generated by Django 4.1.1 on 2022-11-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sekujuru_app', '0003_alter_anime_day_alter_anime_genre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webuser',
            name='d_user',
        ),
        migrations.RemoveField(
            model_name='webuser',
            name='fav_anime',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
        migrations.DeleteModel(
            name='WebUser',
        ),
    ]
