# Generated by Django 4.1.1 on 2022-11-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sekujuru_app', '0004_remove_webuser_d_user_remove_webuser_fav_anime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeplatform',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.CharField(default='-', max_length=999),
        ),
        migrations.AlterField(
            model_name='anime',
            name='platform',
            field=models.ManyToManyField(default=None, to='sekujuru_app.animeplatform'),
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.IntegerField(default=None)),
                ('link', models.CharField(max_length=999)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sekujuru_app.animeplatform')),
            ],
        ),
    ]
