# Generated by Django 4.1.1 on 2022-11-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekujuru_app', '0005_animeplatform_premium_alter_anime_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_image',
            field=models.CharField(default='-', max_length=999),
        ),
    ]
