# Generated by Django 4.1 on 2022-11-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sekujuru_app', '0007_remove_anime_rating_alter_anime_anime_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
