# Generated by Django 4.1.2 on 2022-11-19 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sekujuru_app", "0009_anime_episode"),
    ]

    operations = [
        migrations.RemoveField(model_name="anime", name="episode",),
        migrations.AddField(
            model_name="episode",
            name="anime",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="sekujuru_app.anime",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="episode", unique_together={("anime", "platform")},
        ),
    ]
