# Generated by Django 4.1.2 on 2022-11-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sekujuru_app", "0010_remove_anime_episode_episode_anime_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="episode", unique_together={("anime", "platform", "episode")},
        ),
    ]
